config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 # get 'events/index'
 # get 'events/create'
 # get 'events/show'

 #kod poniższy będzie działać ale trzeba zmienić ścieżki w linkach na te zgodne z rails routes
 # get '/events' => 'events#index'
 # get 'events/new'
 # get 'events/:id' => 'events#show'
 # post '/events' => 'events#create'

 #inna metoda: routing zorientowany na zasoby
 resources :events, :only=>[:index, :new, :create, :show]

  resources :tickets
#  root "tickets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates:artist, :presence=>true
    validates:description, :presence=>false
    validates:price_low, :presence=>true, :numericality=>true
    validates:price_high, :presence=>true, :numericality=>true
    validates:event_date, :presence=>true
    has_many:tickets
    validate:event_date_not_from_past
    validate:min_price_lower_than_max

    def event_date_not_from_past
        if event_date < Date.today
            errors.add('Data wydarzenia','nie może być z przeszłości')
        end
    end

    def min_price_lower_than_max
        if price_low > price_high
            errors.add('Minimalna cena musi być','mniejsza od maksymalnej')
        end
    end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    validates:name, :presence=>true, :length=>{:minimum=>6}
    validates:email_address, :presence=>true
    validates:price, :presence=>true
    validates:seat_id_seq, :presence=>true
    validates:phone, :presence=>true
    belongs_to:event
    belongs_to:user
    validate:price_must_fit_the_range

    def price_must_fit_the_range
      if !price.nil?
        if (price < event.price_low)||(price > event.price_high)
            errors.add('Cena biletu','musi mieścić się w widełkach cenowych wydarzenia')
        end
      end
    end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:tickets

         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def authenticate_user
        unless user_signed_in?
            redirect_to new_user_session_path, notice: "Nie jesteś zalogowany. Zaloguj się"
        end
    end    

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show ]
  before_action :check_logged_in, only: %i[new create]
  before_action :authenticate_user!, except: [:index, :new, :show]

  def index
    @events=Event.all
  end

  def new
    @event=Event.new
  end

  def create
    @event=Event.new(event_params)

      if @event.save
        flash[:komunikat]='Wydarzenie zostało poprawnie stworzone.'
        redirect_to "/events/#{@event.id}"
      else
        render 'new'
      end
  end

  def show
  end
end

private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)
  end

  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |username,password|
      username=="admin" && password=="admin"
    end
  end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new      o co z tym chodzi???
  def new
    @ticket = current_user.tickets.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Bilet został pomyślnie utworzony." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Bilet został pomyślnie zaktualizowany." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Bilet został pomyślnie usunięty." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:event_id, :user_id, :name, :seat_id_seq, :address, :price, :email_address, :phone)
    end

    def correct_user
      @ticket=current_user.tickets.find_by(id: params[:id])
      redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorization_helper.rb
module AuthorizationHelper

    def user_signed_in?
        !current_user.nil?
    end



end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this ticket from being saved:</h2>
  
        <ul>
          <% event.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field new_field">
      <%= form.label :wykonawca %>
      <%= form.text_field :artist %>
    </div>
  
    <div class="field new_field">
      <%= form.label :"opis wydarzenia" %>
      <%= form.text_field :description %>
    </div>
  
    <div class="field new_field">
      <%= form.label :"najniższa cena" %>
      <%= form.text_field :price_low %>
    </div>
  
    <div class="field new_field">
      <%= form.label :"najwyższa cena" %>
      <%= form.text_field :price_high %>
    </div>
  
    <div class="field new_field">
      <%= form.label :"data wydarzenia" %>
      <%= form.date_field :event_date %>
    </div>

    <div class="actions text-center">
      <%= form.submit :"Zapisz wydarzenie", class:'btn btn-info text-dark' %>
    </div>
  <% end %>
  

app/views/events/_new_ticket.html.erb
<div class="container d-flex flex-column align-items-center mx-auto" >
  <h1>Nowy bilet</h1>

  <%= form_with(model: ticket) do |form| %>
      <% if ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
    
          <ul>
            <% ticket.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
      <%= form.hidden_field :event_id %>
      </div>
      
      <div class="field">
      <%= form.hidden_field :user_id %>
      </div>

      <div class="field new_field">
        <%= form.label :imie %>
        <%= form.text_field :name %>
      </div>
    
      <div class="field new_field">
        <%= form.label :miejsce %>
        <%= form.text_field :seat_id_seq %>
      </div>
    
      <div class="field new_field">
        <%= form.label :adres %>
        <%= form.text_area :address %>
      </div>
    
      <div class="field new_field">
        <%= form.label :cena %>
        <%= form.text_field :price %>
      </div>
    
      <div class="field new_field">
        <%= form.label :"adres email" %>
        <%= form.text_field :email_address %>
      </div>
    
      <div class="field new_field">
        <%= form.label :"numer telefonu" %>
        <%= form.text_field :phone %>
      </div>
    
      <div class="actions text-center mt-2">
        <%= form.submit :"Zapisz bilet", class:'btn btn-info text-dark' %>
      </div>
  <% end %>
</div> 

app/views/events/_tickets_list.html.erb
<div class="container d-flex flex-column align-items-center mx-auto" >
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Bilety</h1>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Imie</th>
          <th>Miejsce</th>
          <th>Cena</th>
          <th>Numer eventu</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @event.tickets.each do |ticket| %>
          <tr>
            <td><%= ticket.name %></td>
            <td><%= ticket.seat_id_seq %></td>
            <td><%= ticket.price %></td>
            <td><%= ticket.event_id %></td>
            <td><%= link_to 'Pokaż', ticket, :class => 'text-info' %></td>
            <% if (user_signed_in?) && (ticket.user == current_user) %>
              <td><%= link_to 'Edytuj', edit_ticket_path(ticket), :class => 'text-info' %></td>
              <td><%= link_to 'Usuń', ticket, method: :delete, data: { confirm: 'Czy jesteś pewien, że chcesz usunąć bilet?' }, :class => 'text-info' %></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/index.html.erb
    <section class="jumbotron jumbotron-fluid w-100">           
        <div id="event_list" class="main_content container d-flex flex-column text-info align-items-center" >
            <h1 class="p-4 display-6 fw-bold text-center">Wszystkie wydarzenia</h1>
            <ul>
                <% for event in @events %>
                    <li><%= link_to event.artist, event, :class => 'text-decoration-none text-info fs-5' %></li>
                <%end%>
            </ul>
            <p class="mb-0">
                <button type="button" class="btn btn-info"><%=link_to 'Nowe ogłoszenie', new_event_path, :class => 'text-decoration-none text-dark' %></button>
            </p>
        </div>
    </section>

app/views/events/new.html.erb
<section class="jumbotron2 jumbotron-fluid w-100">
    <div class="main_content container d-flex flex-column align-items-center mx-auto" >
        <h1>Nowe wydarzenie</h1>

        <%= render 'form', event: @event %>

        <p class="navbar-text mb-0">
            <button type="button" class="btn btn-info"><%= link_to 'Wstecz', events_path, :class => 'text-decoration-none text-dark' %></button>
        </p>
    </div>
</section>

app/views/events/show.html.erb
<section class="jumbotron2 jumbotron-fluid w-100">
  <div class="main_content d-flex flex-column align-items-center" >
    <p id="komunikat" class="my_alert"><%= flash[:komunikat] %></p>

    <p>
      <strong>Numer eventu:</strong>
      <%= @event.id %>
    </p>

    <p>
      <strong>Wykonawca:</strong>
      <%= @event.artist %>
    </p>

    <p>
      <strong>Opis wydarzenia:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Najniższa cena:</strong>
      <%= @event.price_low %>
    </p>

    <p>
      <strong>Najwyższa cena:</strong>
      <%= @event.price_high %>
    </p>

    <p>
      <strong>Data wydarzenia:</strong>
      <%= @event.event_date %>
    </p>

    <p class="navbar-text mb-0">
      <button type="button" class="btn btn-info"><%= link_to 'Wstecz', events_path, :class => 'text-decoration-none text-dark' %></button>
    </p>

  

    <% if !user_signed_in? %>
      <strong class="d-flex flex-column align-items-center">Aby kupić bilet musisz się zalogować</strong> 
    <% else %>
      <%=render "new_ticket", ticket: current_user.tickets.new( :event_id=>@event.id) %>
    <% end %>
    <%=render "tickets_list" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>

  <body class="bg-dark text-info">

    <div class="d-flex flex-column">
      
      <nav id="my_navbar" class="navbar navbar-expand-md fixed-top p-2 navbar-dark bg-dark">
      
        <button type="button" class="navbar-toggler navbar-toggler-right ml-auto" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <ul class="navbar-nav" id="navScrollspy2">
            <li class="nav-item font-weight-bold">
              <%= link_to 'Strona główna', '/index.html', :class => 'nav-link text-decoration-none text-info' %>
            </li>
            <li class="nav-item font-weight-bold">
              <%= link_to 'Bilety', tickets_path, :class => 'nav-link text-decoration-none text-info' %>
            </li>

            <li class="nav-item font-weight-bold">
              <%= link_to 'Imprezy', events_path, :class => 'nav-link text-decoration-none text-info' %>
            </li>
          </ul>

          <ul class="navbar-nav" id="navScrollspy">           
            

            <% if user_signed_in? %>
              <li class="nav-item ">
                <span class="nav-link text-info">Zalogowano jako <strong><%= current_user.email %></strong>.</span>
              </li>

              <li class="nav-item ">
                <%= link_to 'Edytuj konto', edit_user_registration_path, :class => 'nav-link text-decoration-none text-info' %>
              </li>

              <li class="nav-item ">
                <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, :class => 'nav-link text-decoration-none text-info' %>
              </li>
            <% else %>
              <li class="nav-item ">
                <%= link_to "Zarejestruj się", new_user_registration_path, :class => 'nav-link text-decoration-none text-info' %>
              </li>

              <li class="nav-item ">
                <%= link_to "Zaloguj się", new_user_session_path, :class => 'nav-link text-decoration-none text-info' %>
              </li>
            <% end %>
          </ul>
        </div>
      
      </nav>

      <% if notice %>
      <p class="alert alert-success my_alert"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger my_alert"><%= alert %></p>
      <% end %>

      <%= yield %>

      <footer>
        <div class="text-center p-4 text-info">
          © 2021 Copyright: MK. Wszystkie prawa zastrzeżone.
        </div>   
      </footer>

    </div>


   
  </body>
</html>

app/views/tickets/_events_list.html.erb
<div id="event_list" class="d-flex flex-column align-items-center mx-auto" >
    <h1>Wszystkie wydarzenia</h1>
    <ul>
        <% for event in Event.all %>
            <li><%= link_to event.artist, event, :class => 'text-decoration-none text-info' %></li>
        <%end%>
    </ul>
</div>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field new_field">
  <%= form.label :"numer eventu" %>
  <%= form.text_field :event_id %>
  </div>

  <div class="field new_field">
  <%= form.hidden_field :user_id %>
  </div>
  
  <div class="field new_field">
    <%= form.label :imie %>
    <%= form.text_field :name %>
  </div>

  <div class="field new_field">
    <%= form.label :miejsce %>
    <%= form.text_field :seat_id_seq %>
  </div>

  <div class="field new_field">
    <%= form.label :adres %>
    <%= form.text_area :address %>
  </div>

  <div class="field new_field">
    <%= form.label :cena %>
    <%= form.text_field :price %>
  </div>

  <div class="field new_field">
    <%= form.label :"adres email" %>
    <%= form.text_field :email_address %>
  </div>

  <div class="field new_field">
    <%= form.label :"numer telefonu" %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions text-center">
    <%= form.submit :"Zapisz bilet", class:'btn btn-info text-dark' %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<section class="jumbotron4 jumbotron-fluid w-100"> 
    <div class="main_content container d-flex flex-column align-items-center mx-auto" >
        <h1>Edycja biletu</h1>

        <%= render 'form', ticket: @ticket %>

        <p class="navbar-text mb-0">
            <button type="button" class="btn btn-info"><%= link_to 'Pokaż', @ticket, :class => 'text-decoration-none text-dark' %></button>
            <button type="button" class="btn btn-info"><%= link_to 'Wstecz', tickets_path, :class => 'text-decoration-none text-dark' %></button>
        </p>

        <%= render 'events_list' %>
    </div>
</section>

app/views/tickets/index.html.erb
<section class="jumbotron3 jumbotron-fluid w-100"> 
  <div class="main_content container d-flex flex-column align-items-center mx-auto">

    <h1 class="text-center">Bilety</h1>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" class="align-middle">Imie</th>
            <th scope="col" class="align-middle">Miejsce</th>
            <th scope="col" class="align-middle">Cena</th>
            <th scope="col" class="align-middle">Numer eventu</th>
            <th scope="col" colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.name %></td>
              <td><%= ticket.seat_id_seq %></td>
              <td><%= ticket.price %></td>
              <td><%= ticket.event_id %></td>
              <td><%= link_to 'Pokaż', ticket, :class => 'text-info' %></td>
              <% if (user_signed_in?) && (ticket.user == current_user) %>
                <td><%= link_to 'Edytuj', edit_ticket_path(ticket), :class => 'text-info' %></td>
                <td><%= link_to 'Usuń', ticket, method: :delete, data: { confirm: 'Czy jesteś pewien, że chcesz usunąć bilet?' }, :class => 'text-info' %></td>
              <% else %>
                <td></td>
                <td></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <p class="navbar-text mb-0">
      <button type="button" class="btn btn-info"><%= link_to 'Nowy bilet', new_ticket_path, :class => 'text-decoration-none text-dark' %></button>
    </p>
    
  </div>
</section>

app/views/tickets/new.html.erb
<section class="jumbotron4 jumbotron-fluid w-100"> 
    <div class="main_content container d-flex flex-column align-items-center mx-auto" >
        <h1>Nowy bilet</h1>

        <%= render 'form', ticket:@ticket %>

        <p class="navbar-text mb-0">
            <button type="button" class="btn btn-info"><%= link_to 'Wstecz', tickets_path, :class => 'text-decoration-none text-dark' %></button>
        </p>

        <%= render 'events_list' %>
    </div>
</section>

app/views/tickets/show.html.erb
<section class="jumbotron4 jumbotron-fluid w-100"> 
  <div class="main_content container d-flex flex-column align-items-center mx-auto" >

    <p>
      <strong>Numer eventu:</strong>
      <%= @ticket.event_id %>
    </p>

    <p>
      <strong>Imie:</strong>
      <%= @ticket.name %>
    </p>

    <p>
      <strong>Miejsce:</strong>
      <%= @ticket.seat_id_seq %>
    </p>

    <% if (user_signed_in?) && (@ticket.user == current_user) %>
      <p>
        <strong>Adres:</strong>
        <%= @ticket.address %>
      </p>
    <% end %>

    <p>
      <strong>Cena:</strong>
      <%= @ticket.price %>
    </p>

    <% if (user_signed_in?) && (@ticket.user == current_user) %>
      <p>
        <strong>Adres email:</strong>
        <%= @ticket.email_address %>
      </p>

      <p>
        <strong>Numer telefonu:</strong>
        <%= @ticket.phone %>
      </p>
    <% end %>
    
    <p class="navbar-text mb-0">
    <% if @ticket.user == current_user %>
      <button type="button" class="btn btn-info"><%= link_to 'Edycja', edit_ticket_path(@ticket), :class => 'text-decoration-none text-dark' %></button>
    <% end %>
    <button type="button" class="btn btn-info"><%= link_to 'Wstecz', tickets_path, :class => 'text-decoration-none text-dark' %></button>
    </p>

  </div>  
</section> 